# App Info
spring.application.name=classflow
server.port=8080

# Security (AWS Cognito)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gFzKBoxUE

# Database (MySQL)
#spring.datasource.url=jdbc:mysql://localhost:3306/classflow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=200604
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# AWS RDS
spring.datasource.url=jdbc:mysql://classflow-db.croufwujbqvh.us-east-1.rds.amazonaws.com:3306/classflow
spring.datasource.username=admin
spring.datasource.password=classflow123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate
#create, create-drop, validate, update, none
spring.jpa.hibernate.ddl-auto=update

# SQL Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS S3
aws.accessKey=
aws.secretKey=
aws.sessionToken=

aws.region=us-east-1
aws.s3.bucket=classflow-submissions

#	Env var config
#aws.accessKey=${AWS_ACCESS_KEY}
#aws.secretKey=${AWS_SECRET_KEY}
#aws.sessionToken=${AWS_SESSION_TOKEN}


#ทำให้หน้าข้อมูล Student ต่อ js ได้
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# AWS EventBridge & SNS
aws.eventbridge.bus=classflow-bus
aws.sns.topic.arn=arn:aws:sns:us-east-1:894565488512:classflow-notifications
