# App Info
spring.application.name=classflow
server.port=8080

# Security (AWS Cognito)
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gFzKBoxUE

# Database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/classflow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=200604
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate
#create, create-drop, validate, update, none
spring.jpa.hibernate.ddl-auto=update

# SQL Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS S3
aws.region=us-east-1
aws.s3.bucket=classflow-submissions

